### ISSUE TITLE
Unsure where to run command OLLAMA_ORIGINS=app://obsidian.md* ollama serve

### ISSUE THREAD

**Issue by paulsybrandy** [jcollingj/caret#13]
Kinda new to Ollama but as instructed I try to run the `OLLAMA_ORIGINS=app://obsidian.md* ollama serve` command in both command prompt (where I run ollama) as well as Powershell but in both I get an error stating that the command was not recognized.

Hoping I am just missing something small, ollama works fine in terminal so unsure what is wrong. Thanks.

![image](https://github.com/user-attachments/assets/7357434e-9b48-4467-bbb8-7a8135edc2eb)

![image](https://github.com/user-attachments/assets/70ac7216-d467-4aaf-b52d-04045e815c57)

**Comment by jcollingj** [comment]
Howdy @paulsybrandy 

The `OLLAMA_ORIGINS` part of that command is to set an environment variable that ollama serve recognizes. Seems like this doesn't work on windows anymore.

Can you refer to the docs here and try setting the environment variable that way.
https://github.com/ollama/ollama/blob/main/docs/faq.md#how-do-i-configure-ollama-server

Copy pasted:
```
Setting environment variables on Windows
On Windows, Ollama inherits your user and system environment variables.

First Quit Ollama by clicking on it in the task bar.

Start the Settings (Windows 11) or Control Panel (Windows 10) application and search for environment variables.

Click on Edit environment variables for your account.

Edit or create a new variable for your user account for OLLAMA_HOST, OLLAMA_MODELS, etc.

Click OK/Apply to save.

Start the Ollama application from the Windows Start menu.
```

Could you try that and let me know? I can update the instructions once we've figured out the right way on windows.

**Comment by paulsybrandy** [comment]
Something else may have set the Environmental variable already because that plug-in works fine on obsidian even though I was not able to run that command. Thank you for replying back to me.

**Comment by jcollingj** [comment]
Sounds good! Closing this then. Feel free to reopen if it continues

**Comment by paulsybrandy** [comment]
Tyvm.
