### ISSUE TITLE
How to add a custom model without a base URL?

### ISSUE THREAD

**Issue by Wooden-Gear** [jcollingj/caret#14]
How to add a custom model without a base URL?

**Comment by jcollingj** [comment]
Hey @Wooden-Gear could you explain more what you mean? What model are you trying to add?

You need the base URL because that's how the client knows where to find the model.

**Comment by Wooden-Gear** [comment]
I can't find the input box for custom URL
Here are examples of other plugins:
![image](https://github.com/user-attachments/assets/b3842592-2a2c-4c24-a2a2-1ca3366e5037)
@jcollingj

**Comment by Wooden-Gear** [comment]
Baseurl and model name should have custom input box
@jcollingj 
I am not a native English speaker, so my expression might not be very clear.

**Comment by jcollingj** [comment]
@Wooden-Gear no worries at all! Could you take a screenshot of the whole page you are looking at by chance? I'm not 100% sure where you are with that one.

In Caret the custom model screen looks like:
<img width="560" alt="Screenshot 2024-08-23 at 8 37 47 AM" src="https://github.com/user-attachments/assets/a407753a-7ba7-4247-8b20-1938132dcb77">

**Comment by Wooden-Gear** [comment]
![image](https://github.com/user-attachments/assets/4630bd77-992a-4991-95e3-b42cee604270)
![image](https://github.com/user-attachments/assets/51ba1b36-148f-4e5d-a0d6-7de9b116f115)
Why is my settings interface different from this?
@jcollingj

**Comment by Wooden-Gear** [comment]
Thanks, solved! I didn't know I needed to use a command to add it, I was looking for the URL in the settings page
@jcollingj
