### ISSUE TITLE
The part about adding a custom model is unclear.

### ISSUE THREAD

**Issue by jkjoker** [jcollingj/caret#18]
I really like this plugin, especially the concept of having conversations within a canvas, which is full of imagination.
However, I encountered a problem when configuring the model.

Here's the process:
Usually, to configure a large model provided by ollama, you need to provide the model name and base URL.
The model I want to add is qwen2.5:3b.

Here's what I filled in when configuring:
![image](https://github.com/user-attachments/assets/494fed9d-62f6-436c-bfa9-d1c6392e2b28)

It didn't work when I used it, and the following prompt appeared:
![image](https://github.com/user-attachments/assets/dd91a686-d33c-4f0b-978b-8ee2fb073915)

I think it's because the parameters are not filled in correctly, but I don't know exactly how to configure it. I would be very grateful if you could give me some suggestions!

(ps: Perhaps the model configuration part of this plugin is too complex. For example, for ollama, the ideal situation would be: as long as ollama is selected, the plugin can automatically detect which models are installed locally and available, and you can see a list of models. Then, when switching models, you can simply check the box.)

Latest update: 
Hey, I just posted about a bug I found, and guess what? I tried again, and it's working now! Cool!
Anyway, I'll keep this issue here and share some other thoughts that might help.

Here's what I've been thinking:

1、I'm still a bit confused about when and how the workflow I set up actually gets used. Can you explain that?
2、The chat history is saved as an XML file, which is a bit hard to read. I think it would be better if it was saved as a Markdown file. All we really need is a timestamp, who said what (user or chatbot), right?

**Comment by jkjoker** [comment]
很神奇的事情发生了：
我刚刚在这里反馈了问题，之后再测试时，发现添加自定义模型成功了。目前可以使用了。
不过我打乱保留这里的问题，并且提供另外的一些反馈，也许有用。

其他使用反馈：
1、设定的工作流在什么时候用上，如何用上？目前没看懂。
2、在对话框中聊天后，保留的聊天记录是xml格式，似乎md格式会更加有可读性——毕竟，一个对话记录需要的要素其实并不多，时间戳、user、chatbot三个信息就够了。

**Comment by jcollingj** [comment]
Howdy @jkjoker I am sorry but I am limited to only english. Is there any way you could repost this in English?

**Comment by jkjoker** [comment]
> Howdy @jkjoker I am sorry but I am limited to only english. Is there any way you could repost this in English?

I apologize for any misunderstandings that may have arisen due to the language barrier. To ensure clarity, I've switched to English.

**Comment by jcollingj** [comment]
Thanks for translating! I really appreciate that! 

To confirm, did you get the custom model working correctly? Just want to double check before moving on from that.

To answer your questions:
1. I'm still a bit confused about when and how the workflow I set up actually gets used. Can you explain that?
When you create a workflow it gets saved as a special markdown file. You can then add this to canvas like any other markdown. When you click the sparkle button that workflow it will then execute, using the connected node as input. A couple screenshots here and link to (incomplete) relevant docs here:
https://caretplugin.ai/workflows/creatingworkflows
<img width="1206" alt="Screenshot 2024-09-22 at 3 00 20 PM" src="https://github.com/user-attachments/assets/7818e7e1-2cbb-48f8-b8be-e94dba905a39">
<img width="783" alt="Screenshot 2024-09-22 at 3 00 13 PM" src="https://github.com/user-attachments/assets/6aaf0fa5-17f2-4e29-9ba3-a49b44f60b3e">


2. The chat history is saved as an XML file, which is a bit hard to read. I think it would be better if it was saved as a Markdown file. All we really need is a timestamp, who said what (user or chatbot), right?
The XML version of the chat history is just intended for storage. When you have a chat history file open you can use the command "Caret: Continue Chat" and it will open that conversation in the chat view again. I think that's the best way to review an old chat.

Does that cover what you are looking for? Or are you trying to use the chat history for something else?

**Comment by jkjoker** [comment]
Thanks for your help! My model configuration is effective now and I can use it smoothly. I've been exploring it a lot recently. 

After reviewing your example, I learned a key point in using workflows: putting requirements first. This form of workflow integrates really well with Canvas. 

Regarding the chat history saving method, I agree with your design - being able to fully restart the conversation next time and continue the dialogue is a unique feature of this plugin.

Honestly, the tips you've shared during our conversation are pure gold! They could really benefit others too.  It would be amazing if these could be incorporated into the official documentation somehow.  Think FAQs: How to add a custom model? How to use workflows effectively?  What about managing chat history?  Just a thought, but it could make a big difference!

**Comment by jcollingj** [comment]
@jkjoker Glad everything is working for you! I do need to add more documentation 😅 I'll get to that eventually.
