### ISSUE TITLE
New questions about the custom model：google? remove?

### ISSUE THREAD

**Issue by jkjoker** [jcollingj/caret#19]
Hi, about the custom model, I've encountered some new issues, maybe you have the right idea：

1. I tried to add Google's model, but it was unsuccessful. 

Google's model is a bit different from others in that it doesn't have a fixed base URL, which I think might be a reason. Maybe adding Google to the default list would be an effective approach. 

I found that Google's Gemini Pro has strong reasoning ability and is very suitable for data analysis. If it can be added successfully, it would be very interesting to do data analysis in Canvas.

2. Another issue is that for custom models that have been added, deleting them through the delete instruction doesn't seem to work, and they can still be seen in the dropdown options. 

thanks!

**Comment by jcollingj** [comment]
@jkjoker You can also use Google Gemini through OpenRouter. That's actually what I would recommend right now. I plan to add separate support for Google models now that you can access them via an API key. But I haven't gotten there yet.

I'm going to close this issue but open ones for:
- Adding google models as it's own provider
- The bug with removing models
