### ISSUE TITLE
Discord link is invalid

### ISSUE THREAD

**Issue by lightningRalf** [jcollingj/caret#3]
You can change the duration for how long the discord is available when creating it.

**Comment by jcollingj** [comment]
Nice, great call! Fixed

**Comment by albertsj1** [comment]
@jcollingj  Discord link is invalid again.

**Comment by jcollingj** [comment]
Hmmm did you click on the `https://discord.gg/8FyGfcH24N` link?

I just checked and it looks fine to me. Maybe it's cached on my side or something though.
